apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tsapi-secret-provider
  namespace: "tsnext"
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/website-410522/secrets/MDB_PASSWORD/versions/1"
        path: "mdb_password"
