---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "tsnext"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment-api"
  namespace: "tsnext"
  labels:
    app: "tsapi"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tsapi"
  template:
    metadata:
      labels:
        app: "tsapi"
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
      - name: "tsapi-1"
        image: "us-central1-docker.pkg.dev/website-410522/tsnext/tsapi:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 1729
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 1
        envFrom:
          - configMapRef:
              name: tsapi-config
        volumeMounts:
          - mountPath: "/var/secrets"
            name: tsapi-secret
          - name: gcsfuse
            mountPath: /tsdata
            readOnly: false
      serviceAccountName: tsnextsa
      volumes:
        - name: tsapi-secret
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: tsapi-secret-provider
        - name: gcsfuse
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: tsnext_bucket
              mountOptions: "implicit-dirs"
