apiVersion: v1
kind: Service
metadata:
  name: tsapi-service
  namespace: tsnext
spec:
  selector:
    app: tsapi
  type: NodePort
  ports:
  - name: tsapu-service-port
    protocol: TCP
    port: 80
    targetPort: 1729
