name: build, test, lint

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run ruff
        run: uv run ruff check .

      - name: updating PATH to enable importing my package
        run: echo "PYTHONPATH=./tsapi" >> $GITHUB_ENV
        shell: bash

      - name: Run tests
        run: uv run pytest tests
