name: build, test, lint

on:
  pull_request:
    branches: main
  push:
    branches: main


jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run ruff
        run: uv run ruff check .

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
            mongodb-version: 8.0

      - name: updating PATH to enable importing my package
        run: | 
            echo "PYTHONPATH=." >> $GITHUB_ENV
            touch .env
            echo "DATA_DIR=." > .env
            echo "MDB_HOST=localhost" >> .env
            echo "MDB_PORT=27017" >> .env
            echo "MDB_NAME=test_tsapidb" >> .env
            echo "SECRETS_DIR=." >> .env
            echo "XXX" >> mdb_password

        shell: bash

      - name: Run tests
        run: uv run pytest

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: githubactions@website-410522.iam.gserviceaccount.com
          workload_identity_provider: projects/52069167239/locations/global/workloadIdentityPools/website-dev-pool/providers/github-actions-provider

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: us-west1-docker.pkg.dev

      - name: Build the Docker image
        run: |
          docker build . -t us-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tsapi:latest
          docker push us-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tsapi:latest
